# Generated by Django 3.2 on 2024-06-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'Пользователь'), ('MODERATOR', 'Модератор'), ('ADMIN', 'Админ')], default='user', max_length=150, verbose_name='Роль'),
        ),
    ]
