# Generated by Django 3.2 on 2024-06-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20240620_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(db_index=True, verbose_name='Год выпуска'),
        ),
    ]
